// <auto-generated />
namespace BICT_POC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validationMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validationMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202101181743254_validationMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
